name: Keep AstroMend API Awake
cat << 'EOF' > .github/workflows/ping-api.yml
name: Keep AstroMend API Awake

on:
  schedule:
    # Every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoint
        run: |
          # Try up to 3 times, 5s apart; don't fail workflow if still unsuccessful
          curl --retry 3 --retry-delay 5 -s https://api.astromend.com/health || true
