name: Keep AstroMend API Awake

on:
  # Manuel tetikleme için
  workflow_dispatch:
  # Her 10 dakikada bir otomatik çalıştır
  schedule:
    - cron: '*/10 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoint
        run: |
          # Sunucuya 3 kez dene, her seferinde 5s bekle; hata verse de
          # workflow’u kırma
          curl --retry 3 --retry-delay 5 -s https://api.astromend.com/health || true

